### ISSUE TITLE
Install issue with Eclipse Oxygen

### ISSUE THREAD

**Issue by ieee8023** [jarrah42/texlipse#3]
I receive this error on Eclipse Oxygen Release Milestone 5 (4.7.0 M5). The plugin won't install.

"An error occurred while installing the items
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Install, operand=null --> [R]net.sourceforge.texlipse 1.5.0, action=).
Failed to prepare partial IU: [R]net.sourceforge.texlipse 1.5.0."

**Comment by jarrah42** [comment]
This is just a clone of Texlipse on sourceforge. I don't think it currently supports Oxygen, but I'd suggest posting something over there.

**Comment by ieee8023** [comment]
Ah ok. Also I made a clone of the install site here in case sourceforge goes away. https://texlipse.github.io/

**Comment by jarrah42** [comment]
We're also trying to get this stood up as an Eclipse Foundation project, so hopefully get some more active development going...
